language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: '3.6'
  # - os: osx
  #   python: '3.6'
  #   osx_image: xcode9.4
git:
  depth: false
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lapack fftw gfortran; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq gcc gfortran liblapack-dev libfftw3-dev ; fi
- pip install Cython 
- pip install numpy
- pip install pytest coveralls pytest-cov
install:
- python setup.py install
script:
- pytest --cov=pamtra2
after_success:
- coveralls