language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: '3.5'
  - os: linux
    dist: trusty
    sudo: required
    python: '3.6'
git:
  depth: false
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq gcc gfortran liblapack-dev libfftw3-dev 
- pip install Cython 
- pip install numpy
- pip install pytest coveralls
- pip install dask[complete]
install:
- python setup.py install
script:
- pytest 
after_success:
- coveralls