channels:
- conda-forge
dependencies:
- cython
- python>=3.6
- numpy
- scipy
- xarray
- dask
- numba
- sphinx
- nbsphinx
- ipykernel
- pandoc
- gxx_linux-64
- gcc_linux-64
- gfortran_linux-64
- fftw
- lapack
- sphinx-autoapi