# Only to create python signature file *pyf

signature : 

	f2py calc_moments.f90 hildebrand_sekhon.f90 report_module.f90 -m pyPamtraRadarMomentsLib -h pyPamtraRadarMomentsLib.pyf

all :
	@echo "Use setup.py file for installation"