!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitradar_simulator(f2pysetupfunc)
      use radar_simulator, only : simulate_radar
      use radar_simulator, only : simulate_radar_one
      external f2pysetupfunc
      call f2pysetupfunc(simulate_radar,simulate_radar_one)
      end subroutine f2pyinitradar_simulator

      
      subroutine f2pyinitradar_spectral_broadening(f2pysetupfunc)
      use radar_spectral_broadening, only : estimate_spectralbroadening
      use radar_spectral_broadening, only : estimate_spectralbroadening_&
     &one
      external f2pysetupfunc
      call f2pysetupfunc(estimate_spectralbroadening,estimate_spectralbr&
     &oadening_one)
      end subroutine f2pyinitradar_spectral_broadening

      
      subroutine f2pyinitrandom_module(f2pysetupfunc)
      use random_module, only : counter
      use random_module, only : get_random
      external f2pysetupfunc
      call f2pysetupfunc(counter,get_random)
      end subroutine f2pyinitrandom_module

      
      subroutine f2pyinitradar_spectrum(f2pysetupfunc)
      use radar_spectrum, only : get_radar_spectrum
      use radar_spectrum, only : get_radar_spectrum_one
      external f2pysetupfunc
      call f2pysetupfunc(get_radar_spectrum,get_radar_spectrum_one)
      end subroutine f2pyinitradar_spectrum

      
      subroutine f2pyinitrescale_spec(f2pysetupfunc)
      use rescale_spec, only : rescale_spectra
      use rescale_spec, only : average_spectra
      use rescale_spec, only : interpolate_spectra
      use rescale_spec, only : locate
      external f2pysetupfunc
      call f2pysetupfunc(rescale_spectra,average_spectra,interpolate_spe&
     &ctra,locate)
      end subroutine f2pyinitrescale_spec

      
      subroutine f2pyinitdia2vel(f2pysetupfunc)
      use dia2vel, only : dia2vel_heymsfield10_particles_ms_as
      use dia2vel, only : dia2vel_heymsfield10_particles
      use dia2vel, only : dia2vel_khvorostyanov01_particles
      use dia2vel, only : dia2vel_khvorostyanov01_spheres
      use dia2vel, only : dia2vel_khvorostyanov01_drops
      use dia2vel, only : dia2vel_foote69_rain
      use dia2vel, only : dia2vel_pavlos_cloud
      use dia2vel, only : dia2vel_metek_rain
      use dia2vel, only : dia2vel_rogers_drops
      use dia2vel, only : dia2vel_rogers_graupel
      use dia2vel, only : dia2vel_power_law
      use dia2vel, only : dia2vel_corrected_power_law
      external f2pysetupfunc
      call f2pysetupfunc(dia2vel_heymsfield10_particles_ms_as,dia2vel_he&
     &ymsfield10_particles,dia2vel_khvorostyanov01_particles,dia2vel_khv&
     &orostyanov01_spheres,dia2vel_khvorostyanov01_drops,dia2vel_foote69&
     &_rain,dia2vel_pavlos_cloud,dia2vel_metek_rain,dia2vel_rogers_drops&
     &,dia2vel_rogers_graupel,dia2vel_power_law,dia2vel_corrected_power_&
     &law)
      end subroutine f2pyinitdia2vel

      
      subroutine f2pyinitreport_module(f2pysetupfunc)
      use report_module, only : info
      use report_module, only : fatal
      use report_module, only : nstatus
      use report_module, only : verbose
      use report_module, only : success
      use report_module, only : status_text
      use report_module, only : warning
      use report_module, only : report
      use report_module, only : assert_true
      use report_module, only : assert_false
      external f2pysetupfunc
      call f2pysetupfunc(info,fatal,nstatus,verbose,success,status_text,&
     &warning,report,assert_true,assert_false)
      end subroutine f2pyinitreport_module


